spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/BoardJPA
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
